pull_request_rules:
  - name: merge automated metals update PRs on CI success
    conditions:
      - author=llity
      - title~=(?i)Update Metals to
      - "check-success~=package metals [x86_64-linux]"
    actions:
      merge:
        method: merge
