#! /usr/bin/env bash

# Shows the output of every command
set +x

activateHM() {
  rm ~/.config/orage/oragerc.bak
  HOME_MANAGER_BACKUP_EXT=bak result/activate
  hm-changes-report
}

rebuild_home_edp() {
  nix build .#homeConfigurations.llity-edp.activationPackage
  activateHM
}

rebuild_home_hdmi() {
  nix build .#homeConfigurations.llity-hdmi.activationPackage
  activateHM
}

rebuild_system() {
  # nix build .#nixosConfigurations.vm-nix.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#vm-nix
}

rebuild_vm() {
  sudo nixos-rebuild build-vm --flake .#vm-nix
}

restart_X() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}

case $1 in
  "edp")
    rebuild_home_edp;;
  "hdmi")
    rebuild_home_hdmi;;
  "restart-x")
    restart_X;;
  "update-fish")
    fish -c fish_update_completions;;
  "system")
    rebuild_system;;
  "vm")
    rebuild_vm;;
  *)
    echo "expected 'edp', 'hdmi', 'restart-x', 'update-fish', 'system' or 'vm'";;
esac
